#!/usr/bin/env python3
"""
Generate Hart–CADMID temporal weights (3 transition profiles) and map R10 strategies.

Inputs:
  - output/topsis_3dist_results.xlsx (generated by script 01)

Outputs:
  - output/hart_cadmid_r10_transition.xlsx
    Sheets:
      Fast, Moderate, Slow  (each contains all phases, all dimensions, all indicators)
      R10_Catalog           (compact legend)
"""
from __future__ import annotations

import os
import math
import re
import pandas as pd
import numpy as np

PHASES = ["Concept", "Assessment", "Design", "Manufacture", "In-service", "Disposal"]
TAU = {p: i/(len(PHASES)-1) for i, p in enumerate(PHASES)}  # normalized lifecycle progress

TRANSITIONS = {
    "Fast": 0.5,
    "Moderate": 1.0,
    "Slow": 2.0,
}

# Hart quadrant base weights (crisp) used as a strategic layer.
# Q1: Internal, Today  | Q2: External, Today | Q3: Internal, Tomorrow | Q4: External, Tomorrow
BASE_QUADRANT_WEIGHT = {"Q1": 1.00, "Q2": 0.75, "Q3": 0.50, "Q4": 0.50}

# Heuristic (editable) keyword rules to infer "Today" vs "Tomorrow" orientation from indicator text.
TODAY_KW = [
    "cost", "transport", "stationkeeping", "delta-v", "refueling", "power", "mass",
    "emergency", "medevac", "training", "preparedness", "communication links",
    "protective", "shield", "radar", "optical", "sensor", "monitoring",
]
TOMORROW_KW = [
    "market", "niche", "governance", "policy", "standards", "interoperability",
    "alignment", "participation", "equitable", "transfer", "data access",
    "reusability", "closed-loop", "resource cycling", "remanufacture", "recycle",
    "predict", "modeling", "decision support", "visualization",
]

def _norm(s: str) -> str:
    return re.sub(r"\s+", " ", str(s).strip().lower())

def infer_internal_external(dimension: str) -> str:
    # By paper logic: Economic/Technological = internal value; Social/Environmental = external value
    d = str(dimension).strip().lower()
    if d in ["economic", "technological", "technical"]:
        return "Internal"
    return "External"

def infer_today_tomorrow(indicator: str) -> str:
    s = _norm(indicator)
    for kw in TODAY_KW:
        if kw in s:
            return "Today"
    for kw in TOMORROW_KW:
        if kw in s:
            return "Tomorrow"
    # fallback: default to Today (conservative / feasibility-driven)
    return "Today"

def infer_quadrant(dimension: str, indicator: str) -> str:
    ie = infer_internal_external(dimension)
    tt = infer_today_tomorrow(indicator)
    if ie == "Internal" and tt == "Today":
        return "Q1"
    if ie == "External" and tt == "Today":
        return "Q2"
    if ie == "Internal" and tt == "Tomorrow":
        return "Q3"
    return "Q4"

def today_tomorrow_weights(phase: str, gamma: float) -> tuple[float,float]:
    tau = TAU[phase]
    w_tom = tau**gamma
    w_today = 1.0 - w_tom
    return w_today, w_tom

# R10 catalog (compact)
R10 = {
    "R0": "Refuse",
    "R1": "Rethink",
    "R2": "Reduce",
    "R3": "Reuse",
    "R4": "Repair",
    "R5": "Refurbish",
    "R6": "Remanufacture",
    "R7": "Repurpose",
    "R8": "Recycle",
    "R9": "Recover",
}

PHASE_R10_SET = {
    "Concept":      ["R0", "R1", "R2"],
    "Assessment":   ["R1", "R2"],
    "Design":       ["R1", "R2", "R3", "R4"],
    "Manufacture":  ["R2", "R5", "R6", "R8"],
    "In-service":   ["R3", "R4", "R5"],
    "Disposal":     ["R7", "R8", "R9"],
}

# Simple keyword-to-R mapping (pick best within the phase set)
INDICATOR_R_PREF = [
    (["isru", "local lunar", "materials", "resource utilization"], ["R2","R3","R8"]),
    (["cost", "transport"], ["R2"]),
    (["market", "niche"], ["R1","R7"]),
    (["model", "modeling", "cost model"], ["R1"]),
    (["communication", "data", "interoperability", "standards"], ["R1","R2"]),
    (["repair", "maintenance", "servicing"], ["R4","R3"]),
    (["reuse", "reusability"], ["R3"]),
    (["recycle", "recycling"], ["R8"]),
    (["recover"], ["R9"]),
    (["refurbish"], ["R5"]),
    (["remanufacture"], ["R6"]),
    (["repurpose"], ["R7"]),
    (["training", "preparedness"], ["R1","R2"]),
]

def assign_r10(phase: str, indicator: str) -> str:
    phase_set = PHASE_R10_SET[phase]
    s = _norm(indicator)
    for kws, prefs in INDICATOR_R_PREF:
        if any(kw in s for kw in kws):
            # pick first preference present in phase set
            for p in prefs:
                if p in phase_set:
                    return p
    # fallback: choose the most "preventive" strategy available in phase
    return phase_set[0]

def main() -> None:
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    in_path = os.path.join(repo_root, "output", "topsis_3dist_results.xlsx")
    out_path = os.path.join(repo_root, "output", "hart_cadmid_r10_transition.xlsx")

    df = pd.read_excel(in_path, sheet_name="TOPSIS_3dist")

    needed = ["Dimension","Indicator","CC_L2","CC_L1","CC_Linf"]
    miss = [c for c in needed if c not in df.columns]
    if miss:
        raise ValueError(f"Missing columns in TOPSIS output: {miss}")

    # Compute quadrant classification once
    df = df.copy()
    df["HartQuadrant"] = [infer_quadrant(d,i) for d,i in zip(df["Dimension"], df["Indicator"])]
    df["InternalExternal"] = [infer_internal_external(d) for d in df["Dimension"]]
    df["TodayTomorrow"] = [infer_today_tomorrow(i) for i in df["Indicator"]]
    df["BaseQuadrantWeight"] = df["HartQuadrant"].map(BASE_QUADRANT_WEIGHT).astype(float)

    with pd.ExcelWriter(out_path, engine="openpyxl") as w:
        # Catalog
        cat = pd.DataFrame([{"Code": k, "Strategy": v} for k,v in R10.items()])
        cat.to_excel(w, index=False, sheet_name="R10_Catalog")

        for prof, gamma in TRANSITIONS.items():
            records = []
            for phase in PHASES:
                w_today, w_tom = today_tomorrow_weights(phase, gamma)
                for _, r in df.iterrows():
                    quad = r["HartQuadrant"]
                    tt = r["TodayTomorrow"]
                    base = r["BaseQuadrantWeight"]
                    phase_factor = (w_today if tt=="Today" else w_tom)
                    hart_cadmid_w = base * phase_factor

                    rec = {
                        "Transition": prof,
                        "Gamma": gamma,
                        "Phase": phase,
                        "Tau": TAU[phase],
                        "Dimension": r["Dimension"],
                        "Indicator": r["Indicator"],
                        "HartQuadrant": quad,
                        "BaseQuadrantWeight": base,
                        "w_Today_phase": w_today,
                        "w_Tomorrow_phase": w_tom,
                        "HartCADMID_weight": hart_cadmid_w,
                        "R10_code": assign_r10(phase, r["Indicator"]),
                        "Priority_L2": float(r["CC_L2"] * hart_cadmid_w),
                        "Priority_L1": float(r["CC_L1"] * hart_cadmid_w),
                        "Priority_Linf": float(r["CC_Linf"] * hart_cadmid_w),
                    }
                    records.append(rec)

            out = pd.DataFrame(records)

            # Ranks within (Dimension, Phase) for each metric
            for m in ["L2","L1","Linf"]:
                out[f"Rank_{m}"] = out.groupby(["Dimension","Phase"])[f"Priority_{m}"].rank(ascending=False, method="min").astype(int)

            # Sort for readability
            out2 = out.sort_values(["Phase","Dimension","Rank_L2","Rank_L1","Rank_Linf"])
            out2.to_excel(w, index=False, sheet_name=prof[:31])

    print(f"Saved: {out_path}")

if __name__ == "__main__":
    main()
